# Generated by Django 2.2.13 on 2021-01-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(default='linhongcun', max_length=20)),
                ('t_age', models.IntegerField(default=21)),
                ('t_image', models.CharField(default='http://itaem.oss-cn-shenzhen.aliyuncs.com/20180509083509.jpg?Expires=4679469344&OSSAccessKeyId=LTAIATBJKsu6vu4R&Signature=PJkwOp9DVhtYu3Xkka0MnZVfnP0%3D', max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='studentInfo',
        ),
    ]
